.pragma library
// Generated by tools/pixelart/bears.py — do not edit by hand.
// The pixel bears' sheets (assets/pixel/bear-<kind>.png): frame size, the
// order of the poses (one column each; row 0 eyes open, row 1 blinking) and,
// per pose, the right paw and the top-centre of the head in art pixels.

var poses = ["stand", "walk0", "walk1", "walk2", "walk3", "wave0", "wave1", "crouch", "jump", "sit", "reach", "sleep"];

var kinds = {
 "dad": {
  "frame": [
   38,
   46
  ],
  "head": [
   26,
   23
  ],
  "poses": {
   "stand": {
    "paw": [
     27.9,
     35.3
    ],
    "head": [
     19.0,
     7
    ],
    "headWidth": 26
   },
   "walk0": {
    "paw": [
     21.7,
     35.6
    ],
    "head": [
     19.0,
     7
    ],
    "headWidth": 26
   },
   "walk1": {
    "paw": [
     23.9,
     37.0
    ],
    "head": [
     19.0,
     9
    ],
    "headWidth": 26
   },
   "walk2": {
    "paw": [
     28.2,
     35.2
    ],
    "head": [
     19.0,
     7
    ],
    "headWidth": 26
   },
   "walk3": {
    "paw": [
     25.1,
     37.0
    ],
    "head": [
     19.0,
     9
    ],
    "headWidth": 26
   },
   "wave0": {
    "paw": [
     29.0,
     19.2
    ],
    "head": [
     19.0,
     7
    ],
    "headWidth": 26
   },
   "wave1": {
    "paw": [
     32.4,
     22.8
    ],
    "head": [
     19.0,
     7
    ],
    "headWidth": 26
   },
   "crouch": {
    "paw": [
     31.4,
     33.6
    ],
    "head": [
     19.0,
     8
    ],
    "headWidth": 26
   },
   "jump": {
    "paw": [
     30.3,
     24.2
    ],
    "head": [
     19.0,
     12
    ],
    "headWidth": 26
   },
   "sit": {
    "paw": [
     28.4,
     40.6
    ],
    "head": [
     19.0,
     13
    ],
    "headWidth": 26
   },
   "reach": {
    "paw": [
     33.4,
     33.8
    ],
    "head": [
     19.0,
     13
    ],
    "headWidth": 26
   },
   "sleep": {
    "paw": [
     31.6,
     38.0
    ],
    "head": [
     19.0,
     14
    ],
    "headWidth": 26
   }
  }
 },
 "mama": {
  "frame": [
   36,
   43
  ],
  "head": [
   25,
   22
  ],
  "poses": {
   "stand": {
    "paw": [
     26.0,
     33.4
    ],
    "head": [
     18.5,
     7
    ],
    "headWidth": 25
   },
   "walk0": {
    "paw": [
     20.5,
     33.6
    ],
    "head": [
     18.5,
     7
    ],
    "headWidth": 25
   },
   "walk1": {
    "paw": [
     22.4,
     35.0
    ],
    "head": [
     18.5,
     9
    ],
    "headWidth": 25
   },
   "walk2": {
    "paw": [
     26.3,
     33.3
    ],
    "head": [
     18.5,
     7
    ],
    "headWidth": 25
   },
   "walk3": {
    "paw": [
     23.6,
     35.0
    ],
    "head": [
     18.5,
     9
    ],
    "headWidth": 25
   },
   "wave0": {
    "paw": [
     27.0,
     19.1
    ],
    "head": [
     18.5,
     7
    ],
    "headWidth": 25
   },
   "wave1": {
    "paw": [
     30.1,
     22.2
    ],
    "head": [
     18.5,
     7
    ],
    "headWidth": 25
   },
   "crouch": {
    "paw": [
     29.1,
     31.5
    ],
    "head": [
     18.5,
     8
    ],
    "headWidth": 25
   },
   "jump": {
    "paw": [
     28.1,
     23.7
    ],
    "head": [
     18.5,
     11
    ],
    "headWidth": 25
   },
   "sit": {
    "paw": [
     26.5,
     37.7
    ],
    "head": [
     18.5,
     12
    ],
    "headWidth": 25
   },
   "reach": {
    "paw": [
     30.9,
     31.6
    ],
    "head": [
     18.5,
     12
    ],
    "headWidth": 25
   },
   "sleep": {
    "paw": [
     29.3,
     35.4
    ],
    "head": [
     18.5,
     13
    ],
    "headWidth": 25
   }
  }
 },
 "cub": {
  "frame": [
   30,
   35
  ],
  "head": [
   21,
   19
  ],
  "poses": {
   "stand": {
    "paw": [
     20.7,
     28.6
    ],
    "head": [
     14.5,
     7
    ],
    "headWidth": 21
   },
   "walk0": {
    "paw": [
     16.6,
     28.7
    ],
    "head": [
     14.5,
     7
    ],
    "headWidth": 21
   },
   "walk1": {
    "paw": [
     18.1,
     30.0
    ],
    "head": [
     14.5,
     9
    ],
    "headWidth": 21
   },
   "walk2": {
    "paw": [
     20.9,
     28.5
    ],
    "head": [
     14.5,
     7
    ],
    "headWidth": 21
   },
   "walk3": {
    "paw": [
     18.9,
     30.0
    ],
    "head": [
     14.5,
     9
    ],
    "headWidth": 21
   },
   "wave0": {
    "paw": [
     21.5,
     17.8
    ],
    "head": [
     14.5,
     7
    ],
    "headWidth": 21
   },
   "wave1": {
    "paw": [
     23.8,
     20.2
    ],
    "head": [
     14.5,
     7
    ],
    "headWidth": 21
   },
   "crouch": {
    "paw": [
     23.1,
     26.9
    ],
    "head": [
     14.5,
     7
    ],
    "headWidth": 21
   },
   "jump": {
    "paw": [
     22.4,
     21.9
    ],
    "head": [
     14.5,
     11
    ],
    "headWidth": 21
   },
   "sit": {
    "paw": [
     21.1,
     32.4
    ],
    "head": [
     14.5,
     11
    ],
    "headWidth": 21
   },
   "reach": {
    "paw": [
     24.4,
     27.8
    ],
    "head": [
     14.5,
     11
    ],
    "headWidth": 21
   },
   "sleep": {
    "paw": [
     23.2,
     30.7
    ],
    "head": [
     14.5,
     12
    ],
    "headWidth": 21
   }
  }
 }
};
