.pragma library
// Generated by tools/pixelart/hero.py — do not edit by hand.
// The featured panel's scenes (assets/pixel/hero-<scene>.png): frame size,
// frames per row, speed, the screen rectangle the app icon sits in (art
// pixels), the rows by time of day (if any) and whether the first frames
// play once as an intro (static before the picture).

var scenes = {
 "cinema": {
  "size": [
   176,
   92
  ],
  "frames": 4,
  "fps": 4,
  "screen": [
   50,
   10,
   76,
   42
  ],
  "times": [],
  "intro": false
 },
 "cabin": {
  "size": [
   176,
   92
  ],
  "frames": 4,
  "fps": 6,
  "screen": [
   70,
   26,
   40,
   30
  ],
  "times": [
   "night",
   "dawn",
   "day",
   "dusk"
  ],
  "intro": true
 },
 "arcade": {
  "size": [
   176,
   92
  ],
  "frames": 4,
  "fps": 3,
  "screen": [
   68,
   18,
   40,
   30
  ],
  "times": [],
  "intro": false
 }
};
