// One of Bear Den's own UI icons (a bear-ear badge with a motif: gear, apps,
// themes, phone, display, home, play, power, about, plus, globe, refresh,
// medal, wave), generated by tools/pixelart/uiicons.py (Pixel, drawn
// unsmoothed) and tools/classicart/uiicons.py (Classic, smooth SVG) into
// assets/pixel/icon-<name>.png and assets/classic/icon-<name>.svg
// (docs/THEMES.md → UI icons). Never a third-party logo.

import QtQuick
import BearDen

Image {
    id: root
    property string name
    property real size: 48 * Theme.scale
    width: size
    height: size
    source: name.length === 0 ? ""
          : World.classic ? "qrc:/qt/qml/BearDen/assets/classic/icon-" + name + ".svg"
          : "qrc:/qt/qml/BearDen/assets/pixel/icon-" + name + ".png"
    // Pixel: whole art pixels (32 per side), never smoothed. Classic: the SVG
    // rendered at the drawn size.
    smooth: World.classic
    sourceSize: World.classic ? Qt.size(Math.ceil(size), Math.ceil(size)) : Qt.size(32, 32)
    fillMode: Image.PreserveAspectFit
}
